### ISSUE TITLE
Context label

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#22]
Is this something we want to do in the extension, or should this be up to the individual studio to implement?

**Comment by mottosso** [comment]
What's your line of thinking here? What would the extension call the Context?

**Comment by tokejepsen** [comment]
Was thinking similar to how Ftrack does their paths; `Ethel and Ernest / q074 / q074c001 / cg_comp` > `[project_name] / [sequence_name] / [shot_name] / [task_name]`
And in the case of asset builds; `Ethel and Ernest / Asset builds / ernest_1940 bike / rigging` > `[project_name] / Asset builds / [asset_name] / [task_name]`

**Comment by mkolar** [comment]
I second that. It's very clear and would fit most of the way of managing project, Folder, database anything.

**Comment by mottosso** [comment]
Hm, interesting. Well, I can't see this work at all, but then again I'm not in a position to fully imagine it. I'll leave it to your best judgement, but could I ask to at least get a glimpse into how this would look from an end-users perspective, perhaps as a quick screen-recording?

**Comment by tokejepsen** [comment]
Here the selector I'm using, which I can contribute to this extension;

``` python
import ftrack

import pyblish.api


@pyblish.api.log
class SelectContextLabel(pyblish.api.Selector):
    """
    """

    order = pyblish.api.Selector.order + 0.2

    def process(self, context):

        # skipping instance if ftrackData isn't present
        if not context.has_data('ftrackData'):
            self.log.info('No ftrackData present. Skipping this instance')
            return

        ftrack_data = context.data('ftrackData')

        # setting context label
        task = ftrack.Task(ftrack_data['Task']['id'])
        path = [task.getName()]
        for p in task.getParents():
            path.append(p.getName())

        path = ' / '.join(list(reversed(path)))
        context.set_data('label', value=path)
```

Which looks like this;
![01](https://cloud.githubusercontent.com/assets/1860085/8301465/f22379cc-1985-11e5-8902-ad09c37517df.PNG)
![02](https://cloud.githubusercontent.com/assets/1860085/8301466/f6013ae8-1985-11e5-9427-f379a19a5b96.PNG)

**Comment by mottosso** [comment]
Ah, I see. How about making that a window title instead? And maybe call `Context` something like `Scene` or `Current File`?

**Comment by tokejepsen** [comment]
> How about making that a window title instead? And maybe call Context something like Scene or Current File?

That might be a better idea, as I'm needing to resize the window to see it all.
Modifying the window title is done through the settings, and not a data member of the context?

**Comment by mottosso** [comment]
That's right, this would couple your plug-in to Pyblish QML.

To be honest, I don't see this as a responsibility of an ftrack extension. It would however make perfect sense to put in a workflow extension.

Maybe it's time to part ways and let pyblish-ftrack be solely about bridging Pyblish with ftrack from a technical standpoint, and less about how things are visualised in the GUI. If you find that something in a workflow extension is general enough, you can always port it. This feature seems too heavily based on opinion and everyone's got a different one of those.

**Comment by mkolar** [comment]
I think we're back to the question about the new UI being needed. I agree that this context label should be there regardless of extension. With option to change it in selectors. I'd simply give user the option to pass an attribute to context, which would get shown in the UI title for example. Let's call it `contextLabel` for argument sake. If this attribute get's passed to context during selection, It shows, if it doesn't get passed a default value shows, which might be a file name for example as that is the most basic representation of the context the way I see it.

But as @mottosso said, this is more of an issue with the QML extension, rather than ftrack. We're finding that the more we use pyblish (lots of publishes daily now), the more we need a different UI, to reflect as current one is a tad too technical looking and people are not very fond of it.

**Comment by mkolar** [comment]
> Ah, I see. How about making that a window title instead? And maybe call Context something like Scene or Current File? 

Perfect! Exactly what I would assume if I knew nothing about pyblish. "Context" evokes something bigger, like a relationship to the rest of the project, which you don't know from just vanilla `context`. Also considering it's appearing in the ui as an instance now, It would be slightly less abstract for artists, if they saw it as 'Scene' rather than 'context'

I know this is a little shotgun/ftrack-ish, but it's exactly what we are doing right now. Adding 'scene' as an instance and ignoring the 'context' in the UI. For artist, at least the ones I've met in the 3 studios where I'm collaborating on a pipeline right now, the understanding is something along the line of.
- Asset/Element/Instance is some part of my file that I want to share, 
- Workfile is my "scene",
- Task I'm working on (e.g. prj1/sc01/sh020/animation) is the context I'm working in.

but this discussion should probably be moved somewhere else, as it has nothing to do with ftrack extension :)

**Comment by tokejepsen** [comment]
Think the conclusion is we'll keep this ftrack extension as minimal as possible, and keep settings customization outside.

**Comment by mottosso** [comment]
> We're finding that the more we use pyblish (lots of publishes daily now), the more we need a different UI, to reflect as current one is a tad too technical looking and people are not very fond of it.

Feel free to bring this up on the forums and we'll talk about it some more.
