### ISSUE TITLE
Any customization is on instances

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#27]
While looking at outputting multiple versions, I find that customizing the data per instance is important.

Could we have `ftrackAssetName` and `ftrackAssetType` operate on the instance?

**Comment by mkolar** [comment]
Absolutely, that makes sense

**Comment by mkolar** [comment]
I'm working on this and it effectively means that we'd have to either remove `AssetVersion` from the `ftrackdata` or store ftrackdata per instance

**Comment by tokejepsen** [comment]
I would probably store per instance, similar to the Deadline extension. Makes it clearer where things are.

**Comment by mkolar** [comment]
I'd rather keep the shared part of `ftrackData` in the context. If we store per instance we might run into troubles down the line and to avoid having to call the server for each instance. Another option might be to store it in context and then copy into each instance and add `assetVersion`, this would however mean that we'd need to run ftrack collector before any instances.

I'm not very keen on any of those solution considering it's only one key from the whole `ftrackData` that is instance specific.

How about we make a new datamember `ftrackAssetVersion` with keys `id` and `number` and use that instead of adding it to the existing `ftrackData`?

**Comment by tokejepsen** [comment]
> How about we make a new datamember ftrackAssetVersion with keys id and number and use that instead of adding it to the existing ftrackData?

True, and we could definitely go with this. I would say that there is a clarity from injecting into the instance,  where we could avoid all the context work. So even the `ftrackAssetName` would be injected into the ftrackData of the instance.

Currently we are copying the ftrack_data for all instances in the validator, in order to write it back to the context. If we had ftrack_data injected to all instances, we wouldn't need to do this.
To avoid querying the server per instance, you could pull the data in the `__init__` method of the class, then inject into instances in the `process` method.

**Comment by mkolar** [comment]
So I have this almost working, however one question arised when doing this. Should be make it compulsory to include ftrack assetName and assetType on the instances  that are supposed to be published to ftrack, or should be try to use some sane defaults when they are missing i.e. task name for both? 

I like the idea of using some defaults if nothing is specified, however it seems like there might be some unexpected behaviour potentially.

**Comment by mottosso** [comment]
When is the artist specifying `assetName` and `assetType`?

Could it be that when an asset is imported/referenced it could come with these attributes, or could they even be part of the environment?

**Comment by mkolar** [comment]
Artist is not specifying those. TD would specify them when collecting the instance. The way it works is that user only needs to append `ftrackComponent` data member to the instance for it to get integrated to ftrack. Extension picks instances with this data and acts on them accordingly.

Now we're adding option to specify `ftrackAssetName` and `ftrackAssetType`. These can however be determined automatically in most cases. If they are missing and can't be determined, validator fails.

I'm afraid they can't be created as attributes upon importing of referencing, because they usually change type afterwards. For instance, animator would have `rig` imported into the scene, but would be outputting `cache` most likely. Possible, but not worth it in my opinion.

**Comment by mottosso** [comment]
> The way it works is that user only needs to append ftrackComponent data member to the instance for it to get integrated to ftrack. Extension picks instances with this data and acts on them accordingly.

Sounds like we've got an intro to the documentation right there, clear and to the point, good stuff.

> Now we're adding option to specify ftrackAssetName and ftrackAssetType. These can however be determined automatically in most cases. If they are missing and can't be determined, validator fails.

I'm assuming these terms make sense if you're an ftrack user. For anyone else, what is the difference between the `ftrackComponent` and these attributes, why not stick with just `ftrackComponent`?

> I'm afraid they can't be created as attributes upon importing of referencing, because they usually change type afterwards. For instance, animator would have rig imported into the scene, but would be outputting cache most likely. Possible, but not worth it in my opinion.

I see what you mean, the way I've seen it dealt with previously is to give them the type of what they output, not of what they are inputted as. In this case, importing/referencing a rig would be given the type "cache", as that is it's output.

**Comment by mkolar** [comment]
[publishing in ftrack](http://ftrack.rtd.ftrack.com/en/latest/developing/api_tutorial/publishing.html)
in ftrack terms:
`Asset` - is the upmost container holding all versions of some piece of work. 
`Version` - numbered state of the work
`component` - actual file output of the asset. You can have more of these per asset, for example model might have LOW RES GEO, HI RES GEO, PREVIEW, PROXY, but render might have different AOVs as components. Purely up to the studio how they want to use it.

**Comment by tokejepsen** [comment]
> Should be make it compulsory to include ftrack assetName and assetType on the instances that are supposed to be published to ftrack, or should be try to use some sane defaults when they are missing i.e. task name for both?

I would give it some defaults, similarly to how it was working before.

> I like the idea of using some defaults if nothing is specified, however it seems like there might be some unexpected behaviour potentially.

What kind of problems are you seeing/expecting?

**Comment by mkolar** [comment]
some unexpected publishes and fails when I tried completely mixing up the variables. 1 existing ftrack asset of different type than task, + One instance without data + one instance with all the data and similar situations. I just didn't get the logic it all right yet. Getting close though :)

**Comment by mottosso** [comment]
> in ftrack terms:

Excellent, this sounds similar to the problems we're facing in [magenta](http://forums.pyblish.com/t/pyblish-magenta/79/105) right now.

Also, this is very good information for the documentation, to include which parts of ftrack is being considered in the extension.
