### ISSUE TITLE
version numbers

### ISSUE THREAD

**Issue by larsbijl** [pyblish/pyblish-ftrack#39]
from a purists point of view if you are using ftrack it's the brains of the operations.
it holds version information about all asset types and should be a single source for this type of info.

the current implementation of this package tries to ascertain version information from the extracted files and set that into ftrack.

this makes sense if for example houdini is in charge of the versioning and your trying to reflect this in ftrack.

but thats going against the principles of a well defined scope. ftrack is a database.
it should be the source for versions and file names.

I'd propose making the setting if versions numbers as optional. allowing people to use it if they want to do so or if they are transitioning.

**Comment by tokejepsen** [comment]
Can't remember the reasoning for basing the version number on the file name. Possibly to reduce the queries to the database.

We are also not necessarily publishing all work file version to ftrack, meaning that an artist could be working v010 while there are only publishing v001 to v005. How would you make sure of the version number in this case?

**Comment by mottosso** [comment]
Ah, I remember having a discussion about this practice at some point in the forums. I think what makes your situation unique @tokejepsen (and @mkolar) is that you couple the work-in-progress version to the published version.

Typically they are two independent branches, which means you increment locally for your work versions - potentially multiple personal branches of versions per artist, it doesn't matter. And then increment a public, common and shared branch for published files.

It's quite subjective though and I'm not sure there is a "right way". The question is how to make a common ftrack library that caters to both practices, without making a mess.

**Comment by larsbijl** [comment]
I agree. at my last place I did it the same way this package is doing it.
but in my current setup all work get's published. this makes it easier to share work in progress scene with others between offices.

**Comment by tokejepsen** [comment]
> but in my current setup all work get's published. this makes it easier to share work in progress scene with others between offices.

Interesting, how do you ensure people are publishing their work in progress?

**Comment by mkolar** [comment]
If you want ftrack to solely control the versioning, you query the latest version existing in the database, iterate it and publish.

On the other hand if you're like us, that artist is responsible for the version they are publishing, you can set it based on their workfile. 

The package doesn't restrict you from working either way. The question here is what should be the default behavior (that is if you're not dealing with versioning in any of your plugins)
1. Take the version number from your scene and explicitly use it
2. Check the last published version on ftrack, iterate it and publish using that number.
3. Not setting version at all and letting ftrack iterate it automatically. This would however cause a bit of an chicken and egg problem, because you want to know the version number before you conform the files (to put it in the filename for example), however you'd not know this number until you push something to the database...

It would be possible to:
- Create the version on ftrack (returns the new version number)
- Use this version number to place the files in correct location with correct name
- Add these integrated files as components to the created version.

I'm totally open to changing the default behavior which is now scenario 1, however I personally am always fan of having control over what we're publishing. 

Realistically whichever we choose, it won't change the fact, that main person responsible for setting the correct version is the developer writing the plugins. We do however, need to keep the option to explicitly set the version. How you determine this version is totally up to you. 

EDIT:
man I shouldn't be writing comments before the morning cofee :smile:, just read this beautifully convoluted thing after myself. Hope it got the point across anyways

**Comment by mkolar** [comment]
> We are also not necessarily publishing all work file version to ftrack, meaning that an artist could be working v010 while there are only publishing v001 to v005. 

We're doing something a bit different. Artist works on v001 and but iterates minor version for his own needs (v001_01, v001_02, v001_03, etc.), when he publishes it creates v001 on ftrack, in published files and iterates his workfile to v002. Next time he comes to the task he continues on v002 and makes minor version for himself again (v002_01, v002_02), after publish, we get v002 of the work and create workfile v003. 

The point is that artist versions independetly, however only within the scope of the next expected version. He knows that he is working on version 2 of the animation, an that is the expected publish from him.

 If we're suddenly missing a version in the sequence (so we get sh001_v001, v002, v004), we know something went weird somewhere and can investigate if needed.

**Comment by tokejepsen** [comment]
With the new workflow for Ftrack's new api, you can choose whatever versioning you want per component.

I would say that it solves this issue.

**Comment by mottosso** [comment]
Don't forget to indicate which version or commit this was fixed in, so users know whether they need to update and what to update to in order to get this feature.

**Comment by tokejepsen** [comment]
Good point. The new api workflow was introduced with https://github.com/pyblish/pyblish-ftrack/commit/f9d5c7b02607ed86ded0532136b4c743581534bf.
