### ISSUE TITLE
Version not renamed

### ISSUE THREAD

**Issue by tokejepsen** [pyblish/pyblish-ftrack#9]
`version` data member of `ftrackData` is not renamed to better reflect ftrack naming conventions; https://github.com/pyblish/pyblish-ftrack/blob/master/pyblish_ftrack/plugins/select_ftrack.py#L61-L62

Suggest to name it `AssetVersion`

**Comment by mottosso** [comment]
Where is `version` in the context coming from? It sounds like a version of the context, e.g. the current file opened in the host, like the `v002` part of `my_scene_v002.mb`.

**Comment by mkolar** [comment]
> Where is version in the context coming from? 

The way it works right now is that it looks for data member `version` in the context. This is exactly as you said version of the context, which user create himself sometime during selection. If it's not in context (so if user hasn't dealt with this himself), select_ftrack tries to find version in filename and uses that.

> Suggest to name it AssetVersion

I've left this small on purpose, because it's an arbitrary data we're adding to `ftrackData`. It's not something we pulled from ftrack database so until we create version it doesn't really correspond to anything in ftrack. That's why originally I had it outside of `ftrackData` just as `context.data['version']`, I've moved it into ftrackData after the discussion we had about it. 

I'd suggest moving it outside ftrackData, as it was and treat it as `context` property. Once we find or create version on ftrack we put it's actual data in `AssetVersion` key in `ftrackData`. That will also eliminate the need for separate `ftrackVersionID` data member which we're using right now to identify a version.

**Comment by mottosso** [comment]
Sounds logical to me.

**Comment by tokejepsen** [comment]
> I've moved it into ftrackData after the discussion we had about it.

Ahh, I see now. That sounds good to me. Maybe keep the version selection as a separate plugin, that could eventually become standalone.

**Comment by mkolar** [comment]
> Maybe keep the version selection as a separate plugin

that's a very good point! Will do.

**Comment by mkolar** [comment]
Fixed in pull request #10
